# Generated by Django 5.2.9 on 2025-12-15 06:55

from django.db import migrations


def seed_data(apps, schema_editor):
    """Seed initial data for Subject, Recommendation, and Session models."""
    Subject = apps.get_model('website', 'Subject')
    Recommendation = apps.get_model('website', 'Recommendation')
    Session = apps.get_model('website', 'Session')
    User = apps.get_model('website', 'User')

    # Insert 4 example subjects (Math, Coding, Physics, AI)
    subjects_data = [
        {'slug': 'math', 'title': 'Math'},
        {'slug': 'coding', 'title': 'Coding'},
        {'slug': 'physics', 'title': 'Physics'},
        {'slug': 'ai', 'title': 'AI'},
    ]
    for subject_data in subjects_data:
        Subject.objects.get_or_create(slug=subject_data['slug'], defaults=subject_data)

    # Insert 3 example recommendations
    recommendations_data = [
        {'title': 'Introduction to Python', 'icon': 'python-icon'},
        {'title': 'Advanced Mathematics', 'icon': 'math-icon'},
        {'title': 'Machine Learning Basics', 'icon': 'ml-icon'},
    ]
    for rec_data in recommendations_data:
        Recommendation.objects.get_or_create(title=rec_data['title'], defaults=rec_data)

    # Create a test user if none exists (needed for sessions)
    user, created = User.objects.get_or_create(
        email='test@edutech.com',
        defaults={
            'name': 'Test User',
            'password_hash': 'pbkdf2_sha256$870000$placeholder$hash',  # Placeholder hash
        }
    )

    # Insert 2 example sessions
    sessions_data = [
        {'title': 'Learning Python Fundamentals', 'subject': 'Coding'},
        {'title': 'Calculus Revision', 'subject': 'Math'},
    ]
    for session_data in sessions_data:
        Session.objects.get_or_create(
            title=session_data['title'],
            defaults={
                'user': user,
                'subject': session_data['subject'],
            }
        )


def reverse_seed_data(apps, schema_editor):
    """Remove seeded data."""
    Subject = apps.get_model('website', 'Subject')
    Recommendation = apps.get_model('website', 'Recommendation')
    Session = apps.get_model('website', 'Session')

    Subject.objects.filter(slug__in=['math', 'coding', 'physics', 'ai']).delete()
    Recommendation.objects.filter(title__in=[
        'Introduction to Python', 'Advanced Mathematics', 'Machine Learning Basics'
    ]).delete()
    Session.objects.filter(title__in=[
        'Learning Python Fundamentals', 'Calculus Revision'
    ]).delete()


class Migration(migrations.Migration):

    dependencies = [
        ("website", "0002_recommendation_subject_session"),
    ]

    operations = [
        migrations.RunPython(seed_data, reverse_seed_data),
    ]
