# Generated by Django 5.2.9 on 2025-12-17 13:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("website", "0003_seed_data"),
    ]

    operations = [
        migrations.AddField(
            model_name="recommendation",
            name="user",
            field=models.ForeignKey(
                default=5,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="recommendations",
                to="website.user",
            ),
            preserve_default=False,
        ),
    ]
