# Generated by Django 5.2.9 on 2026-01-21 18:48

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("website", "0005_conversation_message_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="FocusSession",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("session_date", models.DateField()),
                ("start_time", models.TimeField()),
                ("end_time", models.TimeField()),
                ("duration_minutes", models.IntegerField()),
                ("subject", models.CharField(max_length=100)),
                (
                    "focus_score",
                    models.IntegerField(default=0, help_text="Score from 1-10"),
                ),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="focus_sessions",
                        to="website.user",
                    ),
                ),
            ],
            options={
                "db_table": "focus_sessions",
                "ordering": ["-session_date", "-start_time"],
                "indexes": [
                    models.Index(
                        fields=["user", "-session_date"], name="idx_focus_user_date"
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="StudyStreak",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("study_date", models.DateField()),
                ("minutes_studied", models.IntegerField(default=0)),
                ("tasks_completed", models.IntegerField(default=0)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="study_streaks",
                        to="website.user",
                    ),
                ),
            ],
            options={
                "db_table": "study_streaks",
                "ordering": ["-study_date"],
                "indexes": [
                    models.Index(
                        fields=["user", "-study_date"], name="idx_streak_user_date"
                    )
                ],
                "unique_together": {("user", "study_date")},
            },
        ),
    ]
